[build]
command = "npm run build"
publish = "/dist"
base = "/"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/*"
to = "/src/Pages/ErrorPage/ErrorPage.jsx"
status = 404